// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: token/verifier/service.proto

package verifierconnect

import (
	verifier "buf.build/gen/go/authaas/token-verifier-service/protocolbuffers/go/token/verifier"
	connect "connectrpc.com/connect/v2"
	context "context"
	sync "sync"
)

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "token.verifier.Service"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceDecodeProcedure is the procedure name of the Service's Decode RPC.
	ServiceDecodeProcedure = "/token.verifier.Service/Decode"
)

var (
	serviceDecodeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     verifier.File_token_verifier_service_proto.Services().ByName("Service").Methods().ByName("Decode"),
			Procedure:  ServiceDecodeProcedure,
		}
	})
)

// ServiceClient is a client for the token.verifier.Service service.
type ServiceClient interface {
	// The claims of a signed token. Refuses a token that does not verify.
	Decode(context.Context, *verifier.DecodeRequest) (*verifier.DecodeResponse, error)
}

// NewServiceClient constructs a client for the token.verifier.Service service. Multiple service
// clients may share a single connect.Client.
func NewServiceClient(client *connect.Client) ServiceClient {
	return &serviceClient{client: client}
}

// ServiceHandler is an implementation of the token.verifier.Service service.
type ServiceHandler interface {
	// The claims of a signed token. Refuses a token that does not verify.
	Decode(context.Context, *verifier.DecodeRequest) (*verifier.DecodeResponse, error)
}

// RegisterServiceHandler registers svc as the token.verifier.Service implementation on server.
func RegisterServiceHandler(server *connect.Server, svc ServiceHandler) {
	adapter := serviceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: serviceDecodeSpec(), Handler: adapter.decode},
	)
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Decode(context.Context, *verifier.DecodeRequest) (*verifier.DecodeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "token.verifier.Service.Decode is not implemented")
}

type serviceClient struct {
	client *connect.Client
}

func (c *serviceClient) Decode(ctx context.Context, req *verifier.DecodeRequest) (*verifier.DecodeResponse, error) {
	var res verifier.DecodeResponse
	if err := c.client.CallUnary(ctx, serviceDecodeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type serviceHandler struct{ svc ServiceHandler }

func (h serviceHandler) decode(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req verifier.DecodeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Decode(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
